import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { CodexAppServerClient, CodexAppServerError, codexBinaryCandidates, normalizeSandboxMode, withCodexAppServer } from '../src/app-server.mjs';

async function fakeCodex(t) {
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-appserver-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));
  const log=path.join(dir,'requests.jsonl');const script=path.join(dir,'codex');
  await fs.writeFile(script,`#!/usr/bin/env node\nconst fs=require('fs');const log=process.env.FAKE_CODEX_LOG;let b='';process.stdin.setEncoding('utf8');process.stdin.on('data',c=>{b+=c;while(true){const i=b.indexOf('\\n');if(i<0)return;const l=b.slice(0,i).trim();b=b.slice(i+1);if(!l)continue;const m=JSON.parse(l);fs.appendFileSync(log,JSON.stringify(m)+'\\n');if(m.method==='initialize')out({id:m.id,result:{userAgent:'fake',codexHome:'/tmp/fake',platformFamily:'unix',platformOs:'linux'}});else if(m.method==='account/read')out({id:m.id,result:{account:{type:'chatgpt',email:'user@example.com',planType:'plus'},requiresOpenaiAuth:true}});else if(m.method==='model/list')out({id:m.id,result:{data:[{id:'official-a',model:'official-a',displayName:'Official A',showInPicker:true}],nextCursor:null}});else if(m.method==='thread/start')out({id:m.id,result:{thread:{id:'thread-1'},model:m.params.model,modelProvider:m.params.modelProvider}});else if(m.method==='turn/start'){out({id:m.id,result:{turn:{id:'turn-1',status:'inProgress',items:[]}}});setTimeout(()=>out({method:'turn/completed',params:{threadId:m.params.threadId,turn:{id:'turn-1',status:'completed',items:[{type:'agentMessage',id:'a',text:'APP_SERVER_OK',phase:'final_answer',memoryCitation:null,delivery:null}]}}}),10)}}});function out(x){process.stdout.write(JSON.stringify(x)+'\\n')}\n`,{mode:0o755});
  return {script,log,env:{...process.env,FAKE_CODEX_LOG:log}};
}
async function fakeCodexNoCompletion(t) {const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-appserver-long-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const script=path.join(dir,'codex');await fs.writeFile(script,`#!/usr/bin/env node\nlet b='';process.stdin.setEncoding('utf8');process.stdin.on('data',c=>{b+=c;while(true){const i=b.indexOf('\\n');if(i<0)return;const l=b.slice(0,i).trim();b=b.slice(i+1);if(!l)continue;const m=JSON.parse(l);if(m.method==='initialize')out({id:m.id,result:{}});else if(m.method==='thread/start')out({id:m.id,result:{thread:{id:'long-thread'},model:m.params.model,modelProvider:m.params.modelProvider}});else if(m.method==='turn/start')out({id:m.id,result:{turn:{id:'long-turn',status:'inProgress'}}})}});function out(x){process.stdout.write(JSON.stringify(x)+'\\n')}\n`,{mode:0o755});return script;}

test('Linux discovery includes Codex bundled by the official ChatGPT deb',()=>{const candidates=codexBinaryCandidates({HOME:'/home/test'});assert.equal(candidates[0],'/usr/lib/chatgpt/resources/codex');assert.ok(candidates.includes('/home/test/.local/bin/codex'))});
test('explicit binary override takes priority over desktop and PATH candidates',()=>{const candidates=codexBinaryCandidates({HOME:'/home/test',CODEX_CLI_PATH:'/custom/codex'});assert.equal(candidates[0],'/custom/codex');assert.equal(candidates[1],'/usr/lib/chatgpt/resources/codex')});
test('sandbox aliases normalize to current App Server enum values',()=>{assert.equal(normalizeSandboxMode('workspace-write'),'workspace-write');assert.equal(normalizeSandboxMode('read-only'),'read-only');assert.equal(normalizeSandboxMode('workspaceWrite'),'workspace-write');assert.equal(normalizeSandboxMode('dangerFullAccess'),'danger-full-access');assert.throws(()=>normalizeSandboxMode('wat'),/Unsupported Codex sandbox mode/)});
test('account/read exposes the existing official ChatGPT login without changing it',async(t)=>{const fake=await fakeCodex(t);const c=new CodexAppServerClient({binary:fake.script,env:fake.env,timeoutMs:2000});await c.start();t.after(()=>c.close());const account=await c.getAccount();assert.deepEqual(account,{account:{type:'chatgpt',email:'user@example.com',planType:'plus'},requiresOpenaiAuth:true});const lines=(await fs.readFile(fake.log,'utf8')).trim().split('\n').map(JSON.parse);assert.equal(lines.find(x=>x.method==='account/read').params.refreshToken,false)});
test('model/list is read from real app-server protocol surface',async(t)=>{const fake=await fakeCodex(t);const c=new CodexAppServerClient({binary:fake.script,env:fake.env,timeoutMs:2000});await c.start();t.after(()=>c.close());const models=await c.listModels();assert.equal(models[0].model,'official-a')});
test('cross-provider thread/start sends explicit modelProvider, current sandbox enum, serviceName and effort',async(t)=>{const fake=await fakeCodex(t);const c=new CodexAppServerClient({binary:fake.script,env:fake.env,timeoutMs:2000});await c.start();t.after(()=>c.close());const r=await c.runThread({model:'third-x',modelProvider:'codex_worker_gateway',prompt:'do work',cwd:'/tmp',sandbox:'read-only',effort:'low',timeoutMs:3000});assert.equal(r.output,'APP_SERVER_OK');assert.equal(r.modelProvider,'codex_worker_gateway');assert.equal(r.effort,'low');const lines=(await fs.readFile(fake.log,'utf8')).trim().split('\n').map(JSON.parse);const start=lines.find(x=>x.method==='thread/start');const turn=lines.find(x=>x.method==='turn/start');assert.equal(start.params.modelProvider,'codex_worker_gateway');assert.equal(start.params.model,'third-x');assert.equal(start.params.sandbox,'read-only');assert.equal(start.params.serviceName,'codex-worker-delegation');assert.equal(turn.params.effort,'low')});
test('runThread exposes a non-duplicated observable lifecycle to the Worker task manager',async(t)=>{const fake=await fakeCodex(t);const c=new CodexAppServerClient({binary:fake.script,env:fake.env,timeoutMs:2000});await c.start();t.after(()=>c.close());const events=[];await c.runThread({model:'third-x',modelProvider:'codex_worker_gateway',prompt:'do work',onProgress:(event)=>events.push(event.method),timeoutMs:3000});assert.ok(events.includes('thread/started'));assert.ok(events.includes('turn/started'));assert.equal(events.filter((method)=>method==='turn/completed').length,1)});
test('turn completion deadline can be extended without restarting the App Server',async(t)=>{const script=await fakeCodexNoCompletion(t);const c=new CodexAppServerClient({binary:script,env:{...process.env},timeoutMs:2000});await c.start();t.after(()=>c.close());const pending=c.runThread({model:'third-x',modelProvider:'codex_worker_gateway',prompt:'long task',timeoutMs:100});await new Promise((resolve)=>setTimeout(resolve,25));const extension=c.extendTurnTimeout(1000);assert.equal(extension.pending,false);assert.ok(extension.deadlineAt);await assert.rejects(pending,(error)=>{assert.equal(error.code,'CODEX_TURN_TIMEOUT');return true})});
test('withCodexAppServer has one bounded lifecycle deadline and deterministically reaches the operation phase',async(t)=>{const script=await fakeCodexNoCompletion(t);await assert.rejects(()=>withCodexAppServer(()=>new Promise(()=>{}),{binary:script,env:{...process.env},timeoutMs:2000,overallTimeoutMs:500}),(error)=>{assert.equal(error.code,'CODEX_APP_SERVER_OVERALL_TIMEOUT');assert.equal(error.phase,'operation');assert.equal(error.timeoutMs,500);return true})});
test('JSON-RPC errors preserve code, data, method, and stderr diagnostics',async(t)=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-appserver-error-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const script=path.join(dir,'codex');await fs.writeFile(script,`#!/usr/bin/env node\nprocess.stdin.setEncoding('utf8');process.stdin.on('data',c=>{for(const line of c.trim().split('\\n')){if(!line)continue;const m=JSON.parse(line);if(m.method==='initialize')process.stdout.write(JSON.stringify({id:m.id,result:{}})+'\\n');else process.stdout.write(JSON.stringify({id:m.id,error:{code:-32602,message:'bad request',data:{field:'sandbox'}}})+'\\n') }})`,{mode:0o755});const c=new CodexAppServerClient({binary:script,env:{...process.env},timeoutMs:1000});await c.start();t.after(()=>c.close());await assert.rejects(()=>c.request('thread/start',{}),(error)=>{assert.ok(error instanceof CodexAppServerError);assert.equal(error.code,-32602);assert.deepEqual(error.data,{field:'sandbox'});assert.equal(error.method,'thread/start');assert.match(error.message,/bad request/);return true})});
test('model/list repeated cursors fail instead of looping until an outer timeout',async(t)=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-appserver-cursor-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const script=path.join(dir,'codex');await fs.writeFile(script,`#!/usr/bin/env node\nlet b='';process.stdin.setEncoding('utf8');process.stdin.on('data',c=>{b+=c;while(true){const i=b.indexOf('\\n');if(i<0)return;const l=b.slice(0,i).trim();b=b.slice(i+1);if(!l)continue;const m=JSON.parse(l);const r=m.method==='initialize'?{}:m.method==='model/list'?{data:[],nextCursor:'loop'}:{};process.stdout.write(JSON.stringify({id:m.id,result:r})+'\\n')}})`,{mode:0o755});const c=new CodexAppServerClient({binary:script,timeoutMs:1000});await c.start();t.after(()=>c.close());await assert.rejects(()=>c.listModels(),/repeated cursor/)});
test('unexpected clean App Server exit rejects pending RPC immediately',async(t)=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-appserver-exit-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const script=path.join(dir,'codex');await fs.writeFile(script,`#!/usr/bin/env node\nlet first=true;process.stdin.setEncoding('utf8');process.stdin.on('data',c=>{for(const line of c.trim().split('\\n')){if(!line)continue;const m=JSON.parse(line);if(m.method==='initialize')process.stdout.write(JSON.stringify({id:m.id,result:{}})+'\\n');else if(first){first=false;process.exit(0)}}})`,{mode:0o755});const c=new CodexAppServerClient({binary:script,timeoutMs:5000});await c.start();t.after(()=>c.close());const started=Date.now();await assert.rejects(()=>c.request('account/read',{}),(e)=>e.code==='CODEX_APP_SERVER_EXITED');assert.ok(Date.now()-started<2000)});
