import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { CodexConfigManager, sameTopLevelSelectors } from '../src/codex-config.mjs';

async function tempEnv(t) {const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-config-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));return{CODEX_HOME:path.join(dir,'.codex'),CWD_DATA_DIR:path.join(dir,'data')}}

test('install adds only namespaced command-auth provider and current agent files without changing official selector',async(t)=>{const env=await tempEnv(t);await fs.mkdir(env.CODEX_HOME,{recursive:true});const original='model_provider = "openai"\nmodel = "gpt-official"\n\n[features]\nweb_search = true\n\n[model_providers.keep_me]\nbase_url = "https://keep"\n';await fs.writeFile(path.join(env.CODEX_HOME,'config.toml'),original);const m=new CodexConfigManager({env,gatewayBaseUrl:'http://127.0.0.1:8788/v1'});const result=await m.install();const text=await m.read();assert.equal(result.topLevelPreserved,true);assert.equal(sameTopLevelSelectors(result.selectorsBefore,result.selectorsAfter),true);assert.match(text,/\[model_providers\.codex_worker_gateway\]/);assert.match(text,/wire_api = "responses"/);assert.match(text,/\[model_providers\.codex_worker_gateway\.auth\]/);assert.doesNotMatch(text,/requires_openai_auth\s*=/);assert.match(text,/\[model_providers\.keep_me\]/);assert.match(text,/^model_provider = "openai"/m);assert.match(text,/^model = "gpt-official"/m);assert.doesNotMatch(text,/\[agents\.cwd-worker\]/);const worker=await fs.readFile(path.join(env.CODEX_HOME,'agents','cwd-worker.toml'),'utf8');const verifier=await fs.readFile(path.join(env.CODEX_HOME,'agents','cwd-verifier.toml'),'utf8');assert.match(worker,/name = "cwd-worker"/);assert.match(worker,/provider.*isolated App Server threads/i);assert.match(verifier,/name = "cwd-verifier"/);assert.match(verifier,/independent verifier/i);assert.doesNotMatch(worker,/model_provider/);assert.doesNotMatch(verifier,/model_provider/);assert.equal((await fs.stat(path.join(env.CWD_DATA_DIR,'codex-config-ownership.json'))).mode&0o777,0o600)});

test('install preserves an existing auth.json byte-for-byte',async(t)=>{const env=await tempEnv(t);await fs.mkdir(env.CODEX_HOME,{recursive:true});await fs.writeFile(path.join(env.CODEX_HOME,'config.toml'),'model_provider = "openai"\nmodel = "official"\n');const authPath=path.join(env.CODEX_HOME,'auth.json');const sentinel=Buffer.from('{"OPENAI_API_KEY":null,"tokens":{"access_token":"DO-NOT-TOUCH"}}\n','utf8');await fs.writeFile(authPath,sentinel,{mode:0o600});const before=await fs.readFile(authPath);await new CodexConfigManager({env,gatewayBaseUrl:'http://127.0.0.1:8788/v1'}).install();const after=await fs.readFile(authPath);assert.deepEqual(after,before)});

test('reinstall is idempotent and never duplicates the managed provider or overwrites the original ownership snapshot',async(t)=>{const env=await tempEnv(t);await fs.mkdir(path.join(env.CODEX_HOME,'agents'),{recursive:true});const originalWorker=Buffer.from('name = "user-worker"\ncustom = true\n');await fs.writeFile(path.join(env.CODEX_HOME,'agents','cwd-worker.toml'),originalWorker,{mode:0o640});await fs.writeFile(path.join(env.CODEX_HOME,'config.toml'),'model_provider = "openai"\nmodel = "official"\n');const m=new CodexConfigManager({env});await m.install();const ownershipBefore=await fs.readFile(path.join(env.CWD_DATA_DIR,'codex-config-ownership.json'));await m.install();const ownershipAfter=await fs.readFile(path.join(env.CWD_DATA_DIR,'codex-config-ownership.json'));const text=await m.read();assert.deepEqual(ownershipAfter,ownershipBefore);assert.equal((text.match(/\[model_providers\.codex_worker_gateway\]/g)||[]).length,1);assert.equal((text.match(/\[model_providers\.codex_worker_gateway\.auth\]/g)||[]).length,1);await m.uninstall();assert.deepEqual(await fs.readFile(path.join(env.CODEX_HOME,'agents','cwd-worker.toml')),originalWorker);assert.equal((await fs.stat(path.join(env.CODEX_HOME,'agents','cwd-worker.toml'))).mode&0o777,0o640)});

test('uninstall removes only managed integration and preserves official auth/selectors and unrelated config',async(t)=>{const env=await tempEnv(t);await fs.mkdir(env.CODEX_HOME,{recursive:true});const original='model_provider = "openai"\nmodel = "official"\n\n[features]\nweb_search = true\n\n[model_providers.keep_me]\nbase_url = "https://keep"\n';await fs.writeFile(path.join(env.CODEX_HOME,'config.toml'),original);const authPath=path.join(env.CODEX_HOME,'auth.json');const auth=Buffer.from('{"tokens":{"access_token":"PRESERVE"}}\n');await fs.writeFile(authPath,auth,{mode:0o600});const m=new CodexConfigManager({env});await m.install();const installed=await m.read();assert.match(installed,/codex_worker_gateway/);const result=await m.uninstall();const after=await m.read();assert.equal(result.topLevelPreserved,true);assert.doesNotMatch(after,/codex_worker_gateway/);assert.match(after,/\[model_providers\.keep_me\]/);assert.match(after,/^model_provider = "openai"/m);assert.match(after,/^model = "official"/m);assert.deepEqual(await fs.readFile(authPath),auth);await assert.rejects(fs.access(path.join(env.CODEX_HOME,'agents','cwd-worker.toml')));await assert.rejects(fs.access(path.join(env.CODEX_HOME,'agents','cwd-verifier.toml')));await assert.rejects(fs.access(path.join(env.CWD_DATA_DIR,'codex-config-ownership.json')))});

test('uninstall preserves user edits made to a role that did not exist before project ownership',async(t)=>{const env=await tempEnv(t);await fs.mkdir(env.CODEX_HOME,{recursive:true});await fs.writeFile(path.join(env.CODEX_HOME,'config.toml'),'model_provider = "openai"\nmodel = "official"\n');const m=new CodexConfigManager({env});await m.install();const worker=path.join(env.CODEX_HOME,'agents','cwd-worker.toml');const userEdit='name = "cwd-worker"\ndeveloper_instructions = "my post-install override"\n';await fs.writeFile(worker,userEdit,{mode:0o600});const result=await m.uninstall();assert.equal(await fs.readFile(worker,'utf8'),userEdit);assert.equal(result.roleResults['cwd-worker'],'preserved-user-modification')});

test('reasoning effort is restored only while the project still owns the last written value',async(t)=>{const env=await tempEnv(t);await fs.mkdir(env.CODEX_HOME,{recursive:true});await fs.writeFile(path.join(env.CODEX_HOME,'config.toml'),'model_provider = "openai"\nmodel = "official"\nmodel_reasoning_effort = "medium"\n');let m=new CodexConfigManager({env});await m.install();await m.setReasoningEffort('high');assert.match(await m.read(),/^model_reasoning_effort = "high"/m);await m.uninstall();assert.match(await m.read(),/^model_reasoning_effort = "medium"/m);
const env2=await tempEnv(t);await fs.mkdir(env2.CODEX_HOME,{recursive:true});await fs.writeFile(path.join(env2.CODEX_HOME,'config.toml'),'model_provider = "openai"\nmodel = "official"\n');m=new CodexConfigManager({env:env2});await m.install();await m.setReasoningEffort('high');let text=await m.read();text=text.replace('model_reasoning_effort = "high"','model_reasoning_effort = "low"');await fs.writeFile(path.join(env2.CODEX_HOME,'config.toml'),text);await m.uninstall();assert.match(await m.read(),/^model_reasoning_effort = "low"/m)});
