import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { ResponsesGateway } from '../src/gateway.mjs';

async function listen(server){await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve)});return server.address().port}

test('gateway aborts an in-flight upstream request when downstream Codex disconnects',async(t)=>{let upstreamStarted;const started=new Promise(r=>{upstreamStarted=r});let abortedReason=null;const aborted=new Promise((resolve)=>{abortedReason={resolve}});const store={env:{CWD_PROVIDER_REQUEST_TIMEOUT_MS:'60000'},async read(){return{provider:{baseUrl:'http://provider.test/v1',protocol:'responses',apiKeyCipher:'cipher',headers:{}},models:{main:'m',worker:'m'},routing:{}}},async ensureGatewayToken(){return'A'.repeat(43)},async update(fn){return fn(await this.read())}};const vault={async decrypt(){return'key'}};const fetchImpl=async(_url,options)=>new Promise((_resolve,reject)=>{upstreamStarted();options.signal.addEventListener('abort',()=>{abortedReason.resolve(options.signal.reason);reject(options.signal.reason)},{once:true})});const gateway=new ResponsesGateway({store,vault,fetchImpl});const server=http.createServer((req,res)=>{void gateway.handle(req,res,{model:'m',stream:true}).catch(()=>{})});t.after(()=>server.close());const port=await listen(server);const request=http.request({host:'127.0.0.1',port,path:'/v1/responses',method:'POST',headers:{authorization:`Bearer ${'A'.repeat(43)}`}});request.on('error',()=>{});request.end();await started;request.destroy();const reason=await Promise.race([aborted,new Promise((_,reject)=>setTimeout(()=>reject(new Error('upstream abort not observed')),1500))]);assert.match(String(reason?.message||reason),/downstream/i)});

test('gateway maps its own provider deadline to HTTP 504',async(t)=>{const store={env:{CWD_PROVIDER_REQUEST_TIMEOUT_MS:'1000'},async read(){return{provider:{baseUrl:'http://provider.test/v1',protocol:'responses',apiKeyCipher:'cipher',headers:{}},models:{main:'m',worker:'m'},routing:{}}},async ensureGatewayToken(){return'A'.repeat(43)},async update(fn){return fn(await this.read())}};const vault={async decrypt(){return'key'}};const fetchImpl=async(_url,options)=>new Promise((_resolve,reject)=>options.signal.addEventListener('abort',()=>reject(options.signal.reason),{once:true}));const gateway=new ResponsesGateway({store,vault,fetchImpl});const server=http.createServer((req,res)=>{void gateway.handle(req,res,{model:'m',stream:false}).catch((error)=>{if(!res.headersSent){res.writeHead(500,{'content-type':'application/json'});res.end(JSON.stringify({error:error.message}))}})});t.after(()=>server.close());const port=await listen(server);const response=await fetch(`http://127.0.0.1:${port}/v1/responses`,{method:'POST',headers:{authorization:`Bearer ${'A'.repeat(43)}`},body:'{}'});assert.equal(response.status,504);const body=await response.json();assert.match(body.error.message,/provider request exceeded/)});
