import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { endpoints, listProviderModels, probeProvider, providerHeaders, sanitizeProviderHeaders } from '../src/provider.mjs';

async function listen(handler) { const server = http.createServer(handler); await new Promise((r) => server.listen(0, '127.0.0.1', r)); const { port } = server.address(); return { server, base: `http://127.0.0.1:${port}` }; }

test('normalizes root, /v1, and concrete endpoints', () => {assert.equal(new URL(endpoints('https://x.test').responses).pathname, '/v1/responses');assert.equal(new URL(endpoints('https://x.test/v1').chat).pathname, '/v1/chat/completions');assert.equal(new URL(endpoints('https://x.test/v1/responses').chat).pathname, '/v1/chat/completions');assert.equal(new URL(endpoints('https://x.test/v1/chat/completions').models).pathname, '/v1/models');assert.throws(() => endpoints('ftp://x.test/v1'), /http or https/);assert.throws(() => endpoints('https://u:p@x.test/v1'), /credentials/)});

test('provider extra headers cannot override authentication, framing, or content type', () => {const filtered = sanitizeProviderHeaders({Authorization: 'Bearer attacker','Content-Type': 'text/plain',Host: 'evil.test','Content-Length': '999',Connection: 'close',Cookie: 'secret=1','X-API-Key': 'vendor-key','X-Trace': 'ok','X-Bad': 'line\r\ninjection'});assert.deepEqual(filtered, { 'X-API-Key': 'vendor-key', 'X-Trace': 'ok' });const headers = providerHeaders({ headers: { Authorization: 'Bearer attacker', 'Content-Type': 'text/plain', 'X-API-Key': 'vendor-key' } }, 'real-key');assert.equal(headers.authorization, 'Bearer real-key');assert.equal(headers['content-type'], 'application/json');assert.equal(headers['X-API-Key'], 'vendor-key')});

test('reads and normalizes third-party /v1/models catalog', async (t) => {const { server, base } = await listen((req, res) => {assert.equal(req.url, '/v1/models');assert.equal(req.headers.authorization, 'Bearer k');res.writeHead(200, {'content-type':'application/json'});res.end(JSON.stringify({data:[{id:'model-a',owned_by:'vendor'},{id:'model-b',display_name:'Model B'},{id:'model-a'}]}))});t.after(() => server.close());const models = await listProviderModels({ baseUrl: base, apiKey:'k' });assert.deepEqual(models, [{id:'model-a',name:'model-a',ownedBy:'vendor'},{id:'model-b',name:'Model B',ownedBy:null}])});

test('model catalog bounds rows, identifiers, and body size',async(t)=>{let mode='ids';const {server,base}=await listen((req,res)=>{res.writeHead(200,{'content-type':'application/json'});if(mode==='ids')res.end(JSON.stringify({data:[{id:'x'.repeat(513)},{id:'ok'}]}));else res.end(JSON.stringify({data:Array.from({length:2001},(_,i)=>({id:`m${i}`}))}))});t.after(()=>server.close());assert.deepEqual((await listProviderModels({baseUrl:base,apiKey:'k'})).map(x=>x.id),['ok']);mode='rows';await assert.rejects(()=>listProviderModels({baseUrl:base,apiKey:'k'}),/more than 2000 models/)});

test('probe chooses native Responses when endpoint succeeds without draining an unbounded success stream', async (t) => {const { server, base } = await listen((req, res) => {assert.equal(req.url, '/v1/responses');res.writeHead(200, {'content-type':'text/event-stream'});res.write('data: {"id":"resp"}\n\n');const timer=setInterval(()=>res.write('data: {"delta":"x"}\n\n'),20);res.on('close',()=>clearInterval(timer))});t.after(() => server.close());const result = await probeProvider({ baseUrl: base, apiKey:'k', model:'m' });assert.equal(result.protocol, 'responses');assert.equal(result.ok, true)});

test('probe falls back only on unsupported Responses endpoint', async (t) => {let chatSeen = false;const { server, base } = await listen((req, res) => {if (req.url === '/v1/responses') { res.writeHead(404); res.end('route not found'); return; }if (req.url === '/v1/chat/completions') { chatSeen = true; res.writeHead(200, {'content-type':'application/json'}); res.end('{"choices":[]}'); return; }res.writeHead(500).end()});t.after(() => server.close());const result = await probeProvider({ baseUrl: base, apiKey:'k', model:'m' });assert.equal(result.protocol, 'chat');assert.equal(result.ok, true);assert.equal(chatSeen, true)});

test('probe falls back when a Responses shim exposes a Chat-shaped validation error', async (t) => {let chatSeen = false;const { server, base } = await listen((req, res) => {if (req.url === '/v1/responses') { res.writeHead(400); res.end('{"error":{"message":"missing required parameter: expr_path=messages"}}'); return; }if (req.url === '/v1/chat/completions') { chatSeen = true; res.writeHead(200, {'content-type':'text/event-stream'}); res.end('data: [DONE]\n\n'); return; }res.writeHead(500).end()});t.after(() => server.close());const result = await probeProvider({ baseUrl: base, apiKey:'k', model:'m' });assert.equal(result.protocol, 'chat');assert.equal(result.ok, true);assert.equal(chatSeen, true)});

test('probe does not mask authentication/model errors as chat-only', async (t) => {let chatSeen = false;const { server, base } = await listen((req, res) => {if (req.url === '/v1/responses') { res.writeHead(401); res.end('{"error":"bad key"}'); return; }chatSeen = true; res.writeHead(200).end('{}')});t.after(() => server.close());const result = await probeProvider({ baseUrl: base, apiKey:'bad', model:'m' });assert.equal(result.protocol, 'responses');assert.equal(result.ok, false);assert.equal(result.endpointExists, true);assert.equal(chatSeen, false)});

test('probe rejects oversized model identifiers before network access',async()=>{let calls=0;await assert.rejects(()=>probeProvider({baseUrl:'https://example.test',apiKey:'k',model:'x'.repeat(513),fetchImpl:async()=>{calls++;return new Response('{}')}}),/exceeds 512/);assert.equal(calls,0)});
