import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createApp, executionPlan } from '../src/server.mjs';
import { SecretVault } from '../src/vault.mjs';

const OFFICIAL_MODELS=[
  {id:'official-a',model:'official-a',displayName:'Official A',isDefault:true,supportedReasoningEfforts:[{reasoningEffort:'low'},{reasoningEffort:'high'}],defaultReasoningEffort:'high'},
  {id:'official-main',model:'official-main',displayName:'Official Main',supportedReasoningEfforts:[{reasoningEffort:'high'}],defaultReasoningEffort:'high'},
  {id:'official-worker',model:'official-worker',displayName:'Official Worker',supportedReasoningEfforts:[{reasoningEffort:'low'}],defaultReasoningEffort:'low'},
  {id:'auto-main',model:'auto-main',displayName:'Auto Main',supportedReasoningEfforts:[{reasoningEffort:'high'}],defaultReasoningEffort:'high'}
];
const THIRD_MODELS=[
  {id:'third-a',name:'Third A',supportedReasoningEfforts:['low','max'],defaultReasoningEffort:'low'},
  {id:'third-verifier',name:'Third Verifier',supportedReasoningEfforts:['max'],defaultReasoningEffort:'max'},
  {id:'auto-worker',name:'Auto Worker',supportedReasoningEfforts:['low'],defaultReasoningEffort:'low'},
  {id:'auto-verifier',name:'Auto Verifier',supportedReasoningEfforts:['none'],defaultReasoningEffort:'none'}
];

async function listen(server){await new Promise(r=>server.listen(0,'127.0.0.1',r));return server.address().port}
async function tempApp(t,extraEnv={},fetchImpl=fetch){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-web-'));const env={...process.env,CWD_DATA_DIR:path.join(dir,'data'),CODEX_HOME:path.join(dir,'.codex'),CWD_PORT:'8788',...extraEnv};const app=createApp({env,fetchImpl});const port=await listen(app.server);t.after(async()=>{await app.workerJobs.close('test cleanup');await new Promise((resolve)=>{if(!app.server.listening)return resolve();app.server.close(()=>resolve())});await fs.rm(dir,{recursive:true,force:true,maxRetries:8,retryDelay:25})});return{dir,env,app,base:`http://127.0.0.1:${port}`}}
async function json(base,pathName,method='GET',body){const r=await fetch(base+pathName,{method,headers:{'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const j=await r.json();return{r,j}}
async function waitTask(base,taskId,predicate,timeoutMs=5000){const deadline=Date.now()+timeoutMs;let task=null;while(Date.now()<deadline){task=(await json(base,`/api/worker/status/${encodeURIComponent(taskId)}`)).j;if(predicate(task))return task;await new Promise((resolve)=>setTimeout(resolve,25));}return task}
async function waitAudit(file,predicate,timeoutMs=2000){const deadline=Date.now()+timeoutMs;let audit='';while(Date.now()<deadline){audit=await fs.readFile(file,'utf8').catch(()=> '');if(predicate(audit)){await new Promise((resolve)=>setTimeout(resolve,25));audit=await fs.readFile(file,'utf8').catch(()=> '');if(predicate(audit))return audit;}await new Promise((resolve)=>setTimeout(resolve,25));}return audit}

function catalogFetch(models=THIRD_MODELS){return async(url,options={})=>{const href=String(url);if(href.endsWith('/models'))return new Response(JSON.stringify({data:models}),{status:200,headers:{'content-type':'application/json'}});if(href.endsWith('/responses'))return new Response('{"id":"resp"}',{status:200,headers:{'content-type':'application/json'}});if(href.endsWith('/chat/completions'))return new Response('{"id":"chat"}',{status:200,headers:{'content-type':'application/json'}});throw new Error(`unexpected URL ${href}`)}}

async function fakeCodex(t,{complete=true,oauth=true}={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),complete?'cwd-fake-codex-':'cwd-fake-codex-timeout-'));t.after(()=>fs.rm(dir,{recursive:true,force:true,maxRetries:8,retryDelay:25}));const script=path.join(dir,'codex');const models=JSON.stringify(OFFICIAL_MODELS);await fs.writeFile(script,`#!/usr/bin/env node\nlet b='';const models=${JSON.stringify(models)};process.stdin.setEncoding('utf8');process.stdin.on('data',c=>{b+=c;while(true){const i=b.indexOf('\\n');if(i<0)return;const l=b.slice(0,i).trim();b=b.slice(i+1);if(!l)continue;const m=JSON.parse(l);if(m.method==='initialize')out({id:m.id,result:{}});else if(m.method==='account/read')out({id:m.id,result:${oauth?`{account:{type:'chatgpt',email:'proof@example.com',planType:'plus'},requiresOpenaiAuth:true}`:`{account:null,requiresOpenaiAuth:false}`}});else if(m.method==='model/list')out({id:m.id,result:{data:JSON.parse(models),nextCursor:null}});else if(m.method==='modelProvider/capabilities/read')out({id:m.id,result:{nativeMultiAgent:true,modelCatalog:true}});else if(m.method==='thread/start')out({id:m.id,result:{thread:{id:${complete?`'proof-thread'`:`'timeout-thread'`}},model:m.params.model,modelProvider:m.params.modelProvider}});else if(m.method==='turn/start'){out({id:m.id,result:{turn:{id:${complete?`'turn'`:`'timeout-turn'`},status:'inProgress'}}});${complete?`setTimeout(()=>out({method:'turn/completed',params:{threadId:m.params.threadId,turn:{id:'turn',status:'completed',items:[{type:'agentMessage',text:'CWD_COEXISTENCE_OK'}]}}}),5)`:``}}else if(m.id!==undefined)out({id:m.id,error:{code:-32601,message:'method not found'}})}});function out(x){process.stdout.write(JSON.stringify(x)+'\\n')};setInterval(()=>{},1<<30)\n`,{mode:0o755});return script}

async function configureProvider(app,env,overrides={}){const vault=new SecretVault({env});const apiKeyCipher=await vault.encrypt('secret');return{vault,provider:{name:'New API',baseUrl:'https://new.example/v1',protocol:'auto',apiKeyCipher,headers:{},...overrides}}}

test('Web API saves encrypted provider state and installs isolated Codex integration',async(t)=>{const{env,base}=await tempApp(t);let{r,j:state}=await json(base,'/api/provider','PUT',{baseUrl:'https://new.example/v1',apiKey:'sk-secret',protocol:'auto'});assert.equal(r.status,200);assert.equal(state.provider.hasApiKey,true);assert.equal(JSON.stringify(state).includes('sk-secret'),false);({r,j:state}=await json(base,'/api/codex/install','POST',{}));assert.equal(r.status,200);const config=await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8');assert.match(config,/codex_worker_gateway/);assert.match(config,/\[model_providers\.codex_worker_gateway\.auth\]/);assert.doesNotMatch(config,/requires_openai_auth\s*=/);assert.doesNotMatch(config,/sk-secret/);assert.equal(state.installed,true);await assert.rejects(fs.readFile(path.join(env.CODEX_HOME,'auth.json'),'utf8'),/ENOENT/)});

test('routing API persists independent AUTO and WORKER role routes against live capability catalogs',async(t)=>{const codex=await fakeCodex(t);const{env,base}=await tempApp(t,{CODEX_BIN:codex},catalogFetch());await json(base,'/api/provider','PUT',{baseUrl:'https://new.example/v1',apiKey:'sk-secret',protocol:'auto'});const workerRoles={main:{provider:'official',model:'official-main',effort:'high'},worker:{provider:'official',model:'official-worker',effort:'low'},verifier:{provider:'third_party',model:'third-verifier',effort:'max'}};let{r,j}=await json(base,'/api/routing','PUT',{mode:'DELEGATE',roles:workerRoles});assert.equal(r.status,200,JSON.stringify(j));assert.deepEqual(j.routing.DELEGATE,workerRoles);const autoRoles={main:{provider:'official',model:'auto-main',effort:'high'},worker:{provider:'third_party',model:'auto-worker',effort:'low'},verifier:{provider:'third_party',model:'auto-verifier',effort:'none'}};({r,j}=await json(base,'/api/routing','PUT',{mode:'AUTO',roles:autoRoles}));assert.equal(r.status,200,JSON.stringify(j));assert.deepEqual(j.routing.AUTO,autoRoles);({r,j}=await json(base,'/api/mode','PUT',{mode:'DELEGATE'}));assert.equal(r.status,200);assert.match(await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8'),/model_reasoning_effort = "high"/);({r,j}=await json(base,'/api/worker/run','POST',{role:'worker',task:'implement it'}));assert.equal(r.status,200,JSON.stringify(j));assert.equal(j.execution,'native_subagent_required');assert.equal(j.agentType,'cwd-worker');assert.equal(j.model,'official-worker');assert.equal(j.effort,'low')});

test('execution policy isolates every route involving a third-party provider',()=>{assert.equal(executionPlan({provider:'official'},{provider:'official'},'worker').execution,'native_subagent_required');assert.equal(executionPlan({provider:'third_party'},{provider:'third_party'},'worker').execution,'provider_isolated_thread');assert.equal(executionPlan({provider:'official'},{provider:'third_party'},'worker').execution,'cross_provider_thread');assert.equal(executionPlan({provider:'third_party'},{provider:'official'},'verifier').execution,'cross_provider_thread')});

test('MAIN mode refuses worker delegation before starting any app-server thread',async(t)=>{const{base}=await tempApp(t);await json(base,'/api/mode','PUT',{mode:'MAIN'});const{r,j}=await json(base,'/api/worker/run','POST',{role:'worker',task:'should not run'});assert.equal(r.status,409);assert.equal(j.code,'MAIN_MODE_LOCKED');assert.match(j.error,/MAIN mode disables delegation/)});

test('runtime coexistence proof auto-installs and preserves official selector',async(t)=>{const codex=await fakeCodex(t);const{env,app,base}=await tempApp(t,{CODEX_BIN:codex},catalogFetch());await fs.mkdir(env.CODEX_HOME,{recursive:true});await fs.writeFile(path.join(env.CODEX_HOME,'config.toml'),'model_provider = "openai"\nmodel = "official-a"\n');const {provider}=await configureProvider(app,env);await app.store.write({mode:'DELEGATE',provider,routing:{DELEGATE:{main:{provider:'official',model:'official-a',effort:'high'},worker:{provider:'third_party',model:'third-a',effort:'low'},verifier:{provider:'third_party',model:'third-a',effort:'low'}}},installed:false});const configBefore=await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8');const x=await json(base,'/api/verify/coexistence','POST',{model:'third-a'});assert.equal(x.r.status,200,JSON.stringify(x.j));assert.equal(x.j.ok,true);assert.equal(x.j.integrationInstalled,true);assert.equal(x.j.globalSelectorUntouched,true);assert.equal(x.j.thirdParty.modelProvider,'codex_worker_gateway');assert.equal(x.j.thirdParty.markerObserved,true);assert.equal(x.j.officialChatGPTBefore.type,'chatgpt');assert.equal(x.j.officialChatGPTAfter.type,'chatgpt');const configAfter=await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8');assert.match(configAfter,/codex_worker_gateway/);assert.equal((configAfter.match(/^# --- codex-worker-delegation managed provider ---$/gm)||[]).length,1);assert.notEqual(configAfter,configBefore)});

test('New API connectivity endpoint tests one or many models without exposing the key',async(t)=>{const fetchImpl=async(url,options)=>{if(url.endsWith('/responses')){const body=JSON.parse(options.body);if(body.model==='chat-only')return new Response('not found',{status:404});if(body.model==='bad')return new Response('{"error":"denied"}',{status:401});return new Response('{"id":"resp"}',{status:200,headers:{'content-type':'application/json'}})}if(url.endsWith('/chat/completions'))return new Response('{"id":"chat"}',{status:200,headers:{'content-type':'application/json'}});throw new Error(`unexpected URL ${url}`)};const{base}=await tempApp(t,{},fetchImpl);await json(base,'/api/provider','PUT',{baseUrl:'https://new.example/v1',apiKey:'sk-secret',protocol:'auto'});let{r,j}=await json(base,'/api/provider/connectivity','POST',{models:['good','chat-only','bad']});assert.equal(r.status,200);assert.deepEqual(j.results.map((row)=>[row.model,row.ok,row.protocol]),[['good',true,'responses'],['chat-only',true,'chat'],['bad',false,'responses']]);assert.doesNotMatch(JSON.stringify(j),/sk-secret/)});

test('gateway serves Codex native catalog alongside standard OpenAI model list',async(t)=>{const fetchImpl=async(url)=>{if(url.endsWith('/models'))return new Response(JSON.stringify({data:[{id:'third-a',display_name:'Third A',owned_by:'vendor'}]}),{status:200,headers:{'content-type':'application/json'}});throw new Error(`unexpected URL ${url}`)};const{base,app}=await tempApp(t,{},fetchImpl);await json(base,'/api/provider','PUT',{baseUrl:'https://new.example/v1',apiKey:'sk-secret',protocol:'auto'});const token=await app.store.ensureGatewayToken();let response=await fetch(`${base}/v1/models`,{headers:{authorization:`Bearer ${token}`}});assert.equal(response.status,200);let body=await response.json();assert.deepEqual(body.data.map((row)=>row.id),['third-a']);response=await fetch(`${base}/v1/models?client_version=0.148.0`,{headers:{authorization:`Bearer ${token}`}});assert.equal(response.status,200);body=await response.json();assert.deepEqual(body.models.map((row)=>row.slug),['third-a']);assert.equal(body.models[0].shell_type,'disabled');assert.deepEqual(body.models[0].supported_reasoning_levels,[])});

test('password setup requires confirmation and protects management APIs',async(t)=>{const{base}=await tempApp(t);let{r}=await json(base,'/api/auth/setup','POST',{password:'CorrectHorseBatteryStaple!',confirmPassword:'different'});assert.equal(r.status,400);({r}=await json(base,'/api/auth/setup','POST',{password:'CorrectHorseBatteryStaple!',confirmPassword:'CorrectHorseBatteryStaple!'}));assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');assert.match(cookie,/cwd_session=/);({r}=await json(base,'/api/state'));assert.equal(r.status,401);const authorized=await fetch(`${base}/api/state`,{headers:{cookie}});assert.equal(authorized.status,200)});

test('local passwordless mode is selectable only on an explicitly non-authenticated loopback launch',async(t)=>{const{env,base}=await tempApp(t,{CWD_REQUIRE_AUTH:'0'});let{r,j}=await json(base,'/api/auth/status');assert.equal(r.status,200);assert.equal(j.passwordlessAvailable,true);assert.equal(j.passwordlessLocal,true);assert.equal(j.mode,'local_passwordless');assert.equal(j.required,false);({r,j}=await json(base,'/api/health'));assert.equal(r.status,200);assert.equal(j.authRequired,false);({r}=await json(base,'/api/state'));assert.equal(r.status,200);const password='CorrectHorseBatteryStaple!';({r}=await json(base,'/api/auth/setup','POST',{password,confirmPassword:password}));assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');({r,j}=await json(base,'/api/auth/status'));assert.equal(j.configured,true);assert.equal(j.passwordlessLocal,false);assert.equal(j.required,true);({r}=await json(base,'/api/state'));assert.equal(r.status,401);let response=await fetch(`${base}/api/auth/mode`,{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({mode:'local_passwordless'})});j=await response.json();assert.equal(response.status,200,JSON.stringify(j));assert.equal(j.mode,'local_passwordless');assert.equal(j.passwordlessLocal,true);assert.equal(j.required,false);({r}=await json(base,'/api/state'));assert.equal(r.status,200);({r,j}=await json(base,'/api/auth/status'));assert.equal(j.authenticated,true);const stored=JSON.parse(await fs.readFile(path.join(env.CWD_DATA_DIR,'web-auth.json'),'utf8'));assert.equal(stored.localPasswordless,true);response=await fetch(`${base}/api/auth/mode`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'password'})});j=await response.json();assert.equal(response.status,200,JSON.stringify(j));assert.equal(j.mode,'password');assert.equal(j.required,true);assert.equal(j.authenticated,false);({r}=await json(base,'/api/state'));assert.equal(r.status,401)});

test('forced-auth and non-loopback launches never honor local passwordless mode',async(t)=>{let{base}=await tempApp(t,{CWD_REQUIRE_AUTH:'1'});let{r,j}=await json(base,'/api/auth/status');assert.equal(j.passwordlessAvailable,false);assert.equal(j.passwordlessLocal,false);assert.equal(j.required,true);({r,j}=await json(base,'/api/health'));assert.equal(j.authRequired,true);({r}=await json(base,'/api/state'));assert.equal(r.status,401);({r}=await json(base,'/api/auth/mode','POST',{mode:'local_passwordless'}));assert.equal(r.status,401);({base}=await tempApp(t,{CWD_REQUIRE_AUTH:'0',CWD_HOST:'0.0.0.0'}));({r,j}=await json(base,'/api/auth/status'));assert.equal(j.loopback,false);assert.equal(j.passwordlessAvailable,false);assert.equal(j.passwordlessLocal,false);assert.equal(j.required,true);({r,j}=await json(base,'/api/health'));assert.equal(j.authRequired,true);({r}=await json(base,'/api/state'));assert.equal(r.status,401)});

test('worker start returns a persistent task with progress, heartbeat, events, and result',async(t)=>{const codex=await fakeCodex(t);const{env,app,base}=await tempApp(t,{CODEX_BIN:codex},catalogFetch());const {provider}=await configureProvider(app,env);await app.store.write({mode:'DELEGATE',provider,routing:{DELEGATE:{main:{provider:'official',model:'official-a',effort:'high'},worker:{provider:'third_party',model:'third-a',effort:'low'},verifier:{provider:'third_party',model:'third-a',effort:'low'}}},installed:false});const started=await json(base,'/api/worker/start','POST',{role:'worker',task:'return the worker marker',profile:'quick',timeoutMs:10000});assert.equal(started.r.status,202,JSON.stringify(started.j));assert.match(started.j.taskId,/^wrk_/);assert.equal(started.j.profile,'quick');assert.ok(started.j.lastHeartbeatAt);assert.ok(['queued','running','completed'].includes(started.j.status));const terminalStatuses=new Set(['completed','failed','timed_out','cancelled']);const task=await waitTask(base,started.j.taskId,(candidate)=>terminalStatuses.has(candidate.status),5000);assert.equal(task.status,'completed');assert.equal(task.output,'CWD_COEXISTENCE_OK');assert.ok(task.events.some((event)=>event.type==='worker.started'));assert.ok(task.events.some((event)=>event.type==='thread/started'));assert.equal(task.result.taskId,task.taskId);const persisted=JSON.parse(await fs.readFile(path.join(env.CWD_DATA_DIR,'worker-tasks',`${task.taskId}.json`),'utf8'));assert.equal(persisted.status,'completed');const audit=await fs.readFile(path.join(env.CWD_DATA_DIR,'audit.jsonl'),'utf8');assert.match(audit,new RegExp(`"event":"worker\\.completed"[^\n]*"taskId":"${task.taskId}"`))});

test('worker timeout becomes a visible timed_out task and is audited',async(t)=>{const codex=await fakeCodex(t,{complete:false});const{env,app,base}=await tempApp(t,{CODEX_BIN:codex,CWD_WORKER_AUTO_REVIEW:'0'},catalogFetch());const {provider}=await configureProvider(app,env);await app.store.write({mode:'DELEGATE',provider,routing:{DELEGATE:{main:{provider:'official',model:'official-a',effort:'high'},worker:{provider:'third_party',model:'third-a',effort:'low'},verifier:{provider:'third_party',model:'third-a',effort:'low'}}},installed:false});const started=await json(base,'/api/worker/start','POST',{role:'worker',task:'must time out',timeoutMs:1000});assert.equal(started.r.status,202,JSON.stringify(started.j));let task=started.j;for(let i=0;i<30&&!['timed_out','failed','completed'].includes(task.status);i++){await new Promise((resolve)=>setTimeout(resolve,100));task=(await json(base,`/api/worker/status/${encodeURIComponent(task.taskId)}`)).j;}assert.equal(task.status,'timed_out');assert.equal(task.error.code,'CODEX_TURN_TIMEOUT');assert.ok(task.lastHeartbeatAt);const audit=await fs.readFile(path.join(env.CWD_DATA_DIR,'audit.jsonl'),'utf8');assert.match(audit,new RegExp(`"event":"worker\\.failed"[^\n]*"taskId":"${task.taskId}"[^\n]*"status":"timed_out"`))});

test('worker review checkpoint renews the real App Server deadline and remains root-control-only',async(t)=>{const codex=await fakeCodex(t,{complete:false});const{env,app,base}=await tempApp(t,{CODEX_BIN:codex,CWD_WORKER_AUTO_REVIEW:'0'},catalogFetch());const {provider}=await configureProvider(app,env);await app.store.write({mode:'DELEGATE',provider,routing:{DELEGATE:{main:{provider:'official',model:'official-a',effort:'high'},worker:{provider:'third_party',model:'third-a',effort:'low'},verifier:{provider:'third_party',model:'third-a',effort:'low'}}},installed:false});const started=await json(base,'/api/worker/start','POST',{role:'worker',task:'must reach review',timeoutMs:2000});assert.equal(started.r.status,202,JSON.stringify(started.j));const review=await waitTask(base,started.j.taskId,(task)=>task.reviewDue||['completed','failed','timed_out','cancelled'].includes(task.status),4000);assert.equal(review.reviewDue,true);assert.equal(review.extensionCount,0);const token=await app.store.ensureGatewayToken();const extendedResponse=await fetch(`${base}/internal/worker/extend/${encodeURIComponent(started.j.taskId)}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({extraMs:2000,reason:'progress and scope verified'})});const extended=await extendedResponse.json();assert.equal(extendedResponse.status,200);assert.equal(extended.reviewDue,false);assert.equal(extended.extensionCount,1);assert.ok(Date.parse(extended.deadlineAt)>Date.parse(review.deadlineAt));const publicExtend=await json(base,`/api/worker/extend/${encodeURIComponent(started.j.taskId)}`,'POST',{extraMs:2000});assert.equal(publicExtend.r.status,404);const stopped=await fetch(`${base}/internal/worker/cancel/${encodeURIComponent(started.j.taskId)}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({reason:'review test cleanup'})});assert.equal(stopped.status,200);assert.equal((await stopped.json()).status,'cancelled')});

test('automatic worker supervision cancels heartbeat-only work and audits the decision',async(t)=>{const codex=await fakeCodex(t,{complete:false});const{env,app,base}=await tempApp(t,{CODEX_BIN:codex,CWD_WORKER_HEARTBEAT_MS:'1000',CWD_WORKER_PROGRESS_STALE_MS:'1000',CWD_WORKER_HEARTBEAT_STALE_MS:'3000'},catalogFetch());const {provider}=await configureProvider(app,env);await app.store.write({mode:'DELEGATE',provider,routing:{DELEGATE:{main:{provider:'official',model:'official-a',effort:'high'},worker:{provider:'third_party',model:'third-a',effort:'low'},verifier:{provider:'third_party',model:'third-a',effort:'low'}}},installed:false});const started=await json(base,'/api/worker/start','POST',{role:'worker',task:'must be supervised',profile:'quick',timeoutMs:3000,maxTotalTimeoutMs:5000});assert.equal(started.r.status,202,JSON.stringify(started.j));const task=await waitTask(base,started.j.taskId,(candidate)=>['completed','failed','timed_out','cancelled'].includes(candidate.status),5000);assert.equal(task.status,'cancelled');assert.equal(task.lastReviewDecision,'cancelled');assert.match(task.cancelReason,/没有近期实质进展/);const auditFile=path.join(env.CWD_DATA_DIR,'audit.jsonl');const audit=await waitAudit(auditFile,(value)=>value.includes(`"event":"worker.auto_review"`)&&value.includes(`"taskId":"${task.taskId}"`)&&value.includes(`"decision":"cancelled"`));assert.match(audit,new RegExp(`"event":"worker\\.auto_review"[^\n]*"taskId":"${task.taskId}"[^\n]*"decision":"cancelled"`));assert.match(audit,new RegExp(`"event":"worker\\.cancelled"[^\n]*"taskId":"${task.taskId}"[^\n]*"automatic":true`))});

test('worker cancellation is visible, idempotent, and stops only the task App Server',async(t)=>{const codex=await fakeCodex(t,{complete:false});const{env,app,base}=await tempApp(t,{CODEX_BIN:codex},catalogFetch());const {provider}=await configureProvider(app,env);await app.store.write({mode:'DELEGATE',provider,routing:{DELEGATE:{main:{provider:'official',model:'official-a',effort:'high'},worker:{provider:'third_party',model:'third-a',effort:'low'},verifier:{provider:'third_party',model:'third-a',effort:'low'}}},installed:false});const started=await json(base,'/api/worker/start','POST',{role:'worker',task:'must be cancellable',timeoutMs:20000});assert.equal(started.r.status,202,JSON.stringify(started.j));const running=await waitTask(base,started.j.taskId,(task)=>task.status==='running'||['completed','failed','timed_out','cancelled'].includes(task.status));assert.equal(running.status,'running');const publicCancel=await json(base,`/api/worker/cancel/${encodeURIComponent(started.j.taskId)}`,'POST',{reason:'operator stop'});assert.equal(publicCancel.r.status,404);const token=await app.store.ensureGatewayToken();const internalResponse=await fetch(`${base}/internal/worker/cancel/${encodeURIComponent(started.j.taskId)}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({reason:'operator stop'})});const stopped={r:internalResponse,j:await internalResponse.json()};assert.equal(stopped.r.status,200,JSON.stringify(stopped.j));assert.equal(stopped.j.status,'cancelled');assert.equal(stopped.j.error.code,'WORKER_CANCELLED');assert.equal(stopped.j.cancelReason,'operator stop');assert.ok(stopped.j.cancelledAt);assert.ok(stopped.j.events.some((event)=>event.type==='worker.cancelled'));const final=await waitTask(base,started.j.taskId,(task)=>task.status==='cancelled');assert.equal(final.status,'cancelled');const repeatResponse=await fetch(`${base}/internal/worker/cancel/${encodeURIComponent(started.j.taskId)}`,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({reason:'second stop'})});const repeated={r:repeatResponse,j:await repeatResponse.json()};assert.equal(repeated.r.status,200);assert.equal(repeated.j.status,'cancelled');assert.equal(repeated.j.cancelReason,'operator stop');const audit=await fs.readFile(path.join(env.CWD_DATA_DIR,'audit.jsonl'),'utf8');assert.match(audit,new RegExp(`"event":"worker\\.cancelled"[^\n]*"taskId":"${started.j.taskId}"`));assert.doesNotMatch(audit,new RegExp(`"event":"worker\\.failed"[^\n]*"taskId":"${started.j.taskId}"`))});
