import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createApp, executionPlan } from '../src/server.mjs';
import { StateStore } from '../src/store.mjs';
import { SecretVault } from '../src/vault.mjs';

async function listen(server){await new Promise(r=>server.listen(0,'127.0.0.1',r));return server.address().port}
async function tempApp(t,extraEnv={}){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-web-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const env={...process.env,CWD_DATA_DIR:path.join(dir,'data'),CODEX_HOME:path.join(dir,'.codex'),CWD_PORT:'8788',...extraEnv};const app=createApp({env,fetchImpl:fetch});const port=await listen(app.server);t.after(()=>app.server.close());return{dir,env,app,base:`http://127.0.0.1:${port}`}}
async function json(base,pathName,method='GET',body){const r=await fetch(base+pathName,{method,headers:{'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const j=await r.json();return{r,j}}
async function fakeCodex(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-fake-codex-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const script=path.join(dir,'codex');await fs.writeFile(script,`#!/usr/bin/env node\nlet b='';process.stdin.setEncoding('utf8');process.stdin.on('data',c=>{b+=c;while(true){const i=b.indexOf('\\n');if(i<0)return;const l=b.slice(0,i).trim();b=b.slice(i+1);if(!l)continue;const m=JSON.parse(l);if(m.method==='initialize')out({id:m.id,result:{}});else if(m.method==='account/read')out({id:m.id,result:{account:{type:'chatgpt',email:'proof@example.com',planType:'plus'},requiresOpenaiAuth:true}});else if(m.method==='model/list')out({id:m.id,result:{data:[{id:'official-a',model:'official-a',displayName:'Official A'}],nextCursor:null}});else if(m.method==='thread/start')out({id:m.id,result:{thread:{id:'proof-thread'},model:m.params.model,modelProvider:m.params.modelProvider}});else if(m.method==='turn/start'){out({id:m.id,result:{turn:{id:'turn',status:'inProgress'}}});setTimeout(()=>out({method:'turn/completed',params:{threadId:m.params.threadId,turn:{id:'turn',status:'completed',items:[{type:'agentMessage',text:'CWD_COEXISTENCE_OK'}]}}}),5)}}});function out(x){process.stdout.write(JSON.stringify(x)+'\\n')}\n`,{mode:0o755});return script}

test('Web API saves encrypted provider state and installs isolated Codex integration',async(t)=>{const{env,base}=await tempApp(t);let{r,j:state}=await json(base,'/api/provider','PUT',{baseUrl:'https://new.example/v1',apiKey:'sk-secret',protocol:'auto'});assert.equal(r.status,200);assert.equal(state.provider.hasApiKey,true);assert.equal(JSON.stringify(state).includes('sk-secret'),false);({r,j:state}=await json(base,'/api/codex/install','POST',{}));assert.equal(r.status,200);const config=await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8');assert.match(config,/codex_worker_gateway/);assert.match(config,/\[model_providers\.codex_worker_gateway\.auth\]/);assert.doesNotMatch(config,/requires_openai_auth\s*=/);assert.doesNotMatch(config,/sk-secret/);assert.equal(state.installed,true);await assert.rejects(fs.readFile(path.join(env.CODEX_HOME,'auth.json'),'utf8'),/ENOENT/)});
test('routing API persists every role explicitly and official-to-official worker resolves to native subagent',async(t)=>{const{base}=await tempApp(t);const roles={main:{provider:'official',model:'official-main'},worker:{provider:'official',model:'official-worker'},verifier:{provider:'third_party',model:'third-verifier'}};let{r,j}=await json(base,'/api/routing','PUT',{mode:'DELEGATE',roles});assert.equal(r.status,200);assert.deepEqual(j.routing.DELEGATE,roles);({r,j}=await json(base,'/api/mode','PUT',{mode:'DELEGATE'}));assert.equal(r.status,200);({r,j}=await json(base,'/api/worker/run','POST',{role:'worker',task:'implement it'}));assert.equal(r.status,200);assert.equal(j.execution,'native_subagent_required');assert.equal(j.agentType,'cwd-worker');assert.equal(j.model,'official-worker')});
test('execution policy isolates every route involving a third-party provider',()=>{assert.equal(executionPlan({provider:'official'},{provider:'official'},'worker').execution,'native_subagent_required');assert.equal(executionPlan({provider:'third_party'},{provider:'third_party'},'worker').execution,'provider_isolated_thread');assert.equal(executionPlan({provider:'official'},{provider:'third_party'},'worker').execution,'cross_provider_thread');assert.equal(executionPlan({provider:'third_party'},{provider:'official'},'verifier').execution,'cross_provider_thread')});
test('MAIN mode refuses worker delegation before starting any app-server thread',async(t)=>{const{base}=await tempApp(t);await json(base,'/api/mode','PUT',{mode:'MAIN'});const{r,j}=await json(base,'/api/worker/run','POST',{role:'worker',task:'should not run'});assert.equal(r.status,500);assert.match(j.error,/MAIN mode disables delegation/)});
test('runtime coexistence proof preserves official selector around a third-party thread',async(t)=>{const codex=await fakeCodex(t);const{env,app,base}=await tempApp(t,{CODEX_BIN:codex});await fs.mkdir(env.CODEX_HOME,{recursive:true});await fs.writeFile(path.join(env.CODEX_HOME,'config.toml'),'model_provider = "openai"\nmodel = "official-a"\n');const vault=new SecretVault({env});const apiKeyCipher=await vault.encrypt('secret');await app.store.write({mode:'DELEGATE',provider:{name:'New API',baseUrl:'https://new.example/v1',protocol:'auto',apiKeyCipher,headers:{}},routing:{DELEGATE:{main:{provider:'official',model:'official-a'},worker:{provider:'third_party',model:'third-a'},verifier:{provider:'third_party',model:'third-a'}}},installed:false});let x=await json(base,'/api/codex/install','POST',{});assert.equal(x.r.status,200);const config=await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8');x=await json(base,'/api/verify/coexistence','POST',{model:'third-a'});assert.equal(x.r.status,200);assert.equal(x.j.ok,true);assert.equal(x.j.globalSelectorUntouched,true);assert.equal(x.j.thirdParty.modelProvider,'codex_worker_gateway');assert.equal(x.j.thirdParty.markerObserved,true);assert.equal(x.j.officialChatGPTBefore.type,'chatgpt');assert.equal(x.j.officialChatGPTAfter.type,'chatgpt');assert.equal(await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8'),config)});
