import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { createApp, executionPlan } from '../src/server.mjs';
import { StateStore } from '../src/store.mjs';
import { SecretVault } from '../src/vault.mjs';

async function listen(server){await new Promise(r=>server.listen(0,'127.0.0.1',r));return server.address().port}
async function tempApp(t,extraEnv={},fetchImpl=fetch){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-web-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const env={...process.env,CWD_DATA_DIR:path.join(dir,'data'),CODEX_HOME:path.join(dir,'.codex'),CWD_PORT:'8788',...extraEnv};const app=createApp({env,fetchImpl});const port=await listen(app.server);t.after(()=>app.server.close());return{dir,env,app,base:`http://127.0.0.1:${port}`}}
async function json(base,pathName,method='GET',body){const r=await fetch(base+pathName,{method,headers:{'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});const j=await r.json();return{r,j}}
async function fakeCodex(t){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-fake-codex-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const script=path.join(dir,'codex');await fs.writeFile(script,`#!/usr/bin/env node\nlet b='';process.stdin.setEncoding('utf8');process.stdin.on('data',c=>{b+=c;while(true){const i=b.indexOf('\\n');if(i<0)return;const l=b.slice(0,i).trim();b=b.slice(i+1);if(!l)continue;const m=JSON.parse(l);if(m.method==='initialize')out({id:m.id,result:{}});else if(m.method==='account/read')out({id:m.id,result:{account:{type:'chatgpt',email:'proof@example.com',planType:'plus'},requiresOpenaiAuth:true}});else if(m.method==='model/list')out({id:m.id,result:{data:[{id:'official-a',model:'official-a',displayName:'Official A'}],nextCursor:null}});else if(m.method==='thread/start')out({id:m.id,result:{thread:{id:'proof-thread'},model:m.params.model,modelProvider:m.params.modelProvider}});else if(m.method==='turn/start'){out({id:m.id,result:{turn:{id:'turn',status:'inProgress'}}});setTimeout(()=>out({method:'turn/completed',params:{threadId:m.params.threadId,turn:{id:'turn',status:'completed',items:[{type:'agentMessage',text:'CWD_COEXISTENCE_OK'}]}}}),5)}}});function out(x){process.stdout.write(JSON.stringify(x)+'\\n')}\n`,{mode:0o755});return script}

test('Web API saves encrypted provider state and installs isolated Codex integration',async(t)=>{const{env,base}=await tempApp(t);let{r,j:state}=await json(base,'/api/provider','PUT',{baseUrl:'https://new.example/v1',apiKey:'sk-secret',protocol:'auto'});assert.equal(r.status,200);assert.equal(state.provider.hasApiKey,true);assert.equal(JSON.stringify(state).includes('sk-secret'),false);({r,j:state}=await json(base,'/api/codex/install','POST',{}));assert.equal(r.status,200);const config=await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8');assert.match(config,/codex_worker_gateway/);assert.match(config,/\[model_providers\.codex_worker_gateway\.auth\]/);assert.doesNotMatch(config,/requires_openai_auth\s*=/);assert.doesNotMatch(config,/sk-secret/);assert.equal(state.installed,true);await assert.rejects(fs.readFile(path.join(env.CODEX_HOME,'auth.json'),'utf8'),/ENOENT/)});
test('routing API persists only visible roles, effort, and verifier inherits worker',async(t)=>{const{env,base}=await tempApp(t);const roles={main:{provider:'official',model:'official-main',effort:'high'},worker:{provider:'official',model:'official-worker',effort:'low'},verifier:{provider:'third_party',model:'third-verifier',effort:'max'}};let{r,j}=await json(base,'/api/routing','PUT',{mode:'DELEGATE',roles});assert.equal(r.status,200);assert.deepEqual(j.routing.DELEGATE,{main:roles.main,worker:roles.worker,verifier:{...roles.worker}});({r,j}=await json(base,'/api/mode','PUT',{mode:'DELEGATE'}));assert.equal(r.status,200);assert.match(await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8'),/model_reasoning_effort = "high"/);({r,j}=await json(base,'/api/worker/run','POST',{role:'worker',task:'implement it'}));assert.equal(r.status,200);assert.equal(j.execution,'native_subagent_required');assert.equal(j.agentType,'cwd-worker');assert.equal(j.model,'official-worker');assert.equal(j.effort,'low')});
test('execution policy isolates every route involving a third-party provider',()=>{assert.equal(executionPlan({provider:'official'},{provider:'official'},'worker').execution,'native_subagent_required');assert.equal(executionPlan({provider:'third_party'},{provider:'third_party'},'worker').execution,'provider_isolated_thread');assert.equal(executionPlan({provider:'official'},{provider:'third_party'},'worker').execution,'cross_provider_thread');assert.equal(executionPlan({provider:'third_party'},{provider:'official'},'verifier').execution,'cross_provider_thread')});
test('MAIN mode refuses worker delegation before starting any app-server thread',async(t)=>{const{base}=await tempApp(t);await json(base,'/api/mode','PUT',{mode:'MAIN'});const{r,j}=await json(base,'/api/worker/run','POST',{role:'worker',task:'should not run'});assert.equal(r.status,500);assert.match(j.error,/MAIN mode disables delegation/)});
test('runtime coexistence proof auto-installs and preserves official selector',async(t)=>{const codex=await fakeCodex(t);const{env,app,base}=await tempApp(t,{CODEX_BIN:codex});await fs.mkdir(env.CODEX_HOME,{recursive:true});await fs.writeFile(path.join(env.CODEX_HOME,'config.toml'),'model_provider = "openai"\nmodel = "official-a"\n');const vault=new SecretVault({env});const apiKeyCipher=await vault.encrypt('secret');await app.store.write({mode:'DELEGATE',provider:{name:'New API',baseUrl:'https://new.example/v1',protocol:'auto',apiKeyCipher,headers:{}},routing:{DELEGATE:{main:{provider:'official',model:'official-a'},worker:{provider:'third_party',model:'third-a'},verifier:{provider:'third_party',model:'third-a'}}},installed:false});const configBefore=await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8');const x=await json(base,'/api/verify/coexistence','POST',{model:'third-a'});assert.equal(x.r.status,200);assert.equal(x.j.ok,true);assert.equal(x.j.integrationInstalled,true);assert.equal(x.j.globalSelectorUntouched,true);assert.equal(x.j.thirdParty.modelProvider,'codex_worker_gateway');assert.equal(x.j.thirdParty.markerObserved,true);assert.equal(x.j.officialChatGPTBefore.type,'chatgpt');assert.equal(x.j.officialChatGPTAfter.type,'chatgpt');const configAfter=await fs.readFile(path.join(env.CODEX_HOME,'config.toml'),'utf8');assert.match(configAfter,/codex_worker_gateway/);assert.equal((configAfter.match(/^# --- codex-worker-delegation managed provider ---$/gm)||[]).length,1);assert.notEqual(configAfter,configBefore)});
test('New API connectivity endpoint tests one or many models without exposing the key',async(t)=>{const fetchImpl=async(url,options)=>{if(url.endsWith('/responses')){const body=JSON.parse(options.body);if(body.model==='chat-only')return new Response('not found',{status:404});if(body.model==='bad')return new Response('{"error":"denied"}',{status:401});return new Response('{"id":"resp"}',{status:200,headers:{'content-type':'application/json'}})}if(url.endsWith('/chat/completions'))return new Response('{"id":"chat"}',{status:200,headers:{'content-type':'application/json'}});throw new Error(`unexpected URL ${url}`)};const{base}=await tempApp(t,{},fetchImpl);await json(base,'/api/provider','PUT',{baseUrl:'https://new.example/v1',apiKey:'sk-secret',protocol:'auto'});let{r,j}=await json(base,'/api/provider/connectivity','POST',{models:['good','chat-only','bad']});assert.equal(r.status,200);assert.deepEqual(j.results.map((row)=>[row.model,row.ok,row.protocol]),[['good',true,'responses'],['chat-only',true,'chat'],['bad',false,'responses']]);assert.doesNotMatch(JSON.stringify(j),/sk-secret/)});
test('gateway serves Codex native catalog alongside standard OpenAI model list',async(t)=>{const fetchImpl=async(url)=>{if(url.endsWith('/models'))return new Response(JSON.stringify({data:[{id:'third-a',display_name:'Third A',owned_by:'vendor'}]}),{status:200,headers:{'content-type':'application/json'}});throw new Error(`unexpected URL ${url}`)};const{base,app}=await tempApp(t,{},fetchImpl);await json(base,'/api/provider','PUT',{baseUrl:'https://new.example/v1',apiKey:'sk-secret',protocol:'auto'});const token=await app.store.ensureGatewayToken();let response=await fetch(`${base}/v1/models`,{headers:{authorization:`Bearer ${token}`}});assert.equal(response.status,200);let body=await response.json();assert.deepEqual(body.data.map((row)=>row.id),['third-a']);response=await fetch(`${base}/v1/models?client_version=0.148.0`,{headers:{authorization:`Bearer ${token}`}});assert.equal(response.status,200);body=await response.json();assert.deepEqual(body.models.map((row)=>row.slug),['third-a']);assert.equal(body.models[0].shell_type,'disabled');assert.deepEqual(body.models[0].supported_reasoning_levels,[]);});
test('password setup requires confirmation and protects management APIs',async(t)=>{const{base}=await tempApp(t);let{r}=await json(base,'/api/auth/setup','POST',{password:'CorrectHorseBatteryStaple!',confirmPassword:'different'});assert.equal(r.status,400);({r}=await json(base,'/api/auth/setup','POST',{password:'CorrectHorseBatteryStaple!',confirmPassword:'CorrectHorseBatteryStaple!'}));assert.equal(r.status,200);const cookie=r.headers.get('set-cookie');assert.match(cookie,/cwd_session=/);({r}=await json(base,'/api/state'));assert.equal(r.status,401);const authorized=await fetch(`${base}/api/state`,{headers:{cookie}});assert.equal(authorized.status,200)});
