import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { StateStore, publicState, activeRouting } from '../src/store.mjs';
import { dataDir } from '../src/paths.mjs';

const sleep=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms));
const execFileAsync=promisify(execFile);

test('v1 state migrates to compact per-mode provider/model routing',async(t)=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-state-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const env={CWD_DATA_DIR:dir};await fs.writeFile(path.join(dir,'state.json'),JSON.stringify({schemaVersion:1,mode:'AUTO',models:{main:'m-main',worker:'m-worker',verifier:'m-ver'},mainSource:'official',provider:{name:'x',apiKeyCipher:'cipher'},protocolCache:{}}));const s=await new StateStore({env}).read();assert.equal(s.schemaVersion,4);assert.equal(s.routing.AUTO.main.provider,'official');assert.equal(s.routing.AUTO.worker.provider,'official');assert.equal(s.routing.AUTO.worker.model,'m-main');assert.equal(s.routing.AUTO.main.effort,'auto');assert.equal(activeRouting(s).verifier.model,'m-main');assert.equal(s.routing.DELEGATE.worker.provider,'third_party');assert.equal(s.routing.DELEGATE.worker.model,'m-worker');assert.equal(s.routing.DELEGATE.worker.effort,'auto')});

test('publicState redacts ciphertext without mutating source and reports hasApiKey',()=>{const s={schemaVersion:2,mode:'AUTO',provider:{name:'x',apiKeyCipher:'secret'},models:{},routing:{AUTO:{main:{provider:'official',model:''},worker:{provider:'third_party',model:''},verifier:{provider:'third_party',model:''}},DELEGATE:{main:{provider:'official',model:''},worker:{provider:'third_party',model:''},verifier:{provider:'third_party',model:''}},MAIN:{main:{provider:'official',model:''},worker:{provider:'official',model:''},verifier:{provider:'official',model:''}}},protocolCache:{}};const p=publicState(s);assert.equal(p.provider.hasApiKey,true);assert.equal('apiKeyCipher'in p.provider,false);assert.equal(s.provider.apiKeyCipher,'secret')});

test('gateway token creation is stable under concurrent first access',async(t)=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-token-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const store=new StateStore({env:{CWD_DATA_DIR:dir}});const tokens=await Promise.all(Array.from({length:20},()=>store.ensureGatewayToken()));assert.equal(new Set(tokens).size,1);assert.equal((await fs.readFile(path.join(dir,'gateway.token'),'utf8')).trim(),tokens[0]);assert.equal((await fs.stat(path.join(dir,'gateway.token'))).mode&0o777,0o600);
});

test('gateway token publication is atomic across independent StateStore instances',async(t)=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-token-multi-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const env={CWD_DATA_DIR:dir};const stores=Array.from({length:24},()=>new StateStore({env}));const tokens=await Promise.all(stores.map((store)=>store.ensureGatewayToken()));assert.equal(new Set(tokens).size,1);assert.match(tokens[0],/^[A-Za-z0-9_-]{43}$/);assert.equal((await fs.readFile(path.join(dir,'gateway.token'),'utf8')).trim(),tokens[0]);const leftovers=(await fs.readdir(dir)).filter((name)=>name.includes('.toktmp'));assert.deepEqual(leftovers,[])});

test('state updates are serialized within a control-plane store instance',async(t)=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-state-serial-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const store=new StateStore({env:{CWD_DATA_DIR:dir}});await store.write({mode:'AUTO',protocolCache:{}});await Promise.all(Array.from({length:20},(_,i)=>store.update(async(s)=>{await sleep(i%3);s.protocolCache[`m${i}`]={protocol:'chat'};return s})));const state=await store.read();assert.equal(Object.keys(state.protocolCache).length,20)});

test('state updates are serialized across independent StateStore instances',async(t)=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-state-cross-instance-lock-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const env={CWD_DATA_DIR:dir};const stores=Array.from({length:16},()=>new StateStore({env}));await stores[0].write({mode:'AUTO',protocolCache:{}});await Promise.all(stores.map((store,i)=>store.update(async(s)=>{await sleep(i%4);s.protocolCache[`x${i}`]={protocol:'chat'};return s})));const state=await stores[0].read();assert.equal(Object.keys(state.protocolCache).filter((key)=>key.startsWith('x')).length,16);assert.equal(await fs.access(path.join(dir,'state.json.lock')).then(()=>true).catch(()=>false),false)});

test('state file lock prevents lost updates across independent OS processes',async(t)=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cwd-state-cross-process-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const store=new StateStore({env:{CWD_DATA_DIR:dir}});await store.write({mode:'AUTO',protocolCache:{}});const moduleUrl=new URL('../src/store.mjs',import.meta.url).href;const code=`const [moduleUrl,dir,key]=process.argv.slice(1);const {StateStore}=await import(moduleUrl);const store=new StateStore({env:{CWD_DATA_DIR:dir}});await store.update(async(s)=>{await new Promise(r=>setTimeout(r,(Number(key)%4)*10));s.protocolCache['p'+key]={protocol:'chat'};return s});`;await Promise.all(Array.from({length:8},(_,i)=>execFileAsync(process.execPath,['--input-type=module','-e',code,moduleUrl,dir,String(i)],{timeout:10000,maxBuffer:1024*1024})));const state=await store.read();assert.equal(Object.keys(state.protocolCache).filter((key)=>key.startsWith('p')).length,8);assert.equal(await fs.access(path.join(dir,'state.json.lock')).then(()=>true).catch(()=>false),false)});

test('default data directory follows HOME identity and ignores ambient XDG_DATA_HOME',()=>{const env={HOME:'/srv/chatgpt-root',XDG_DATA_HOME:'/tmp/wrong-user-data'};assert.equal(dataDir(env),'/srv/chatgpt-root/.local/share/codex-worker-delegation')});
